# Model configurations
model:
  # Mamba-Diffusion Configuration
  mamba_diffusion:
    hidden_dim: 768
    mamba_d_state: 16
    mamba_d_conv: 4
    mamba_expand: 2
    num_diffusion_steps: 1000
    noise_schedule: "cosine"
    max_edges_per_panel: 39
    max_panels_per_pattern: 37
    edge_feature_dim: 9
    text_max_length: 256
    num_layers: 12
    num_heads: 8
    dropout: 0.1

  # NeRF-Fashion Configuration  
  nerf_fashion:
    nerf_pos_encoding_levels: 10
    nerf_dir_encoding_levels: 4
    nerf_hidden_dim: 256
    nerf_num_layers: 8
    gaussian_dim: 32
    max_gaussians: 100000
    mamba_dim: 768
    mamba_depth: 12
    physics_steps: 10
    image_size: 512
    num_samples: 64

  # Base Models (VAE/GAN)
  vae:
    latent_dim: 128
    image_size: 64
    input_channels: 3
    hidden_dims: [32, 64, 128, 256, 512]
    beta: 4.0

  gan:
    z_dim: 128
    num_classes: 10
    embed_dim: 50
    img_size: 64

# Training configuration
training:
  batch_size: 16
  learning_rate: 1e-4
  num_epochs: 100
  device: "cuda"
  mixed_precision: true
  gradient_clip: 1.0
  
  # Optimizer
  optimizer: "adamw"
  weight_decay: 0.01
  betas: [0.9, 0.999]
  
  # Scheduler
  scheduler: "cosine"
  warmup_epochs: 10

# Data configuration
data:
  dataset: "fashion_mnist"  # Options: fashion_mnist, deepfashion, custom
  data_dir: "./data"
  batch_size: 16
  num_workers: 4
  augment: true
  
  # For custom datasets
  custom_metadata: "./data/metadata.json"

# Logging configuration
logging:
  log_dir: "./logs"
  checkpoint_dir: "./checkpoints"
  log_freq: 100
  save_freq: 1000
  sample_freq: 500
  
  # Weights & Biases
  wandb:
    enabled: true
    project: "ai-fashion-design"
    entity: "your-username"

# Generation configuration
generation:
  num_samples: 16
  guidance_scale: 7.5
  num_inference_steps: 50
  output_dir: "./outputs"
  export_format: "dxf"  # Options: dxf, png, obj